function escapeHtml(value) {
  if (value == null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

async function blobToBase64(blob) {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    binary += String.fromCharCode.apply(null, chunk);
  }
  if (typeof btoa === 'function') return btoa(binary);
  return Buffer.from(binary, 'binary').toString('base64');
}

const PLACEHOLDER_DESCRIPTION = 'Describe this Step';

const STYLE = `
  :root { color-scheme: light; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    margin: 0; padding: 40px 24px; background: #fafafa; color: #111;
    max-width: 960px; margin-inline: auto;
  }
  h1 { font-size: 28px; margin: 0 0 8px; }
  .guide-description { color: #555; margin: 0 0 32px; }
  .step { margin-bottom: 40px; }
  .step-label { font-size: 13px; font-weight: 600; color: #92400E; letter-spacing: 0.04em; text-transform: uppercase; }
  .step-description { font-size: 18px; margin: 6px 0 12px; min-width: 0; word-break: break-word; }
  .step-description.placeholder { color: #9ca3af; font-style: italic; }
  .step img {
    display: block; width: 100%; height: auto;
    border: 1px solid #e5e7eb; border-radius: 8px; background: #fff;
  }
  footer { color: #9ca3af; font-size: 12px; text-align: center; padding-top: 32px; border-top: 1px solid #e5e7eb; }
`;

async function exportHtml(guide) {
  const title = guide && guide.title ? guide.title : 'Untitled Guide';
  const description = guide && guide.description ? guide.description : '';
  const steps = Array.isArray(guide && guide.steps) ? guide.steps : [];

  const renderedSteps = await Promise.all(steps.map(async (step, index) => {
    const base64 = step.screenshotBlob ? await blobToBase64(step.screenshotBlob) : '';
    const mime = (step.screenshotBlob && step.screenshotBlob.type) || 'image/jpeg';
    const src = base64 ? `data:${mime};base64,${base64}` : '';
    const hasDescription = typeof step.description === 'string' && step.description.trim() !== '';
    const descriptionHtml = hasDescription
      ? `<p class="step-description">${escapeHtml(step.description)}</p>`
      : `<p class="step-description placeholder">${escapeHtml(PLACEHOLDER_DESCRIPTION)}</p>`;
    const imgHtml = src
      ? `<img src="${src}" alt="${escapeHtml(`Step ${index + 1} screenshot`)}">`
      : '';
    return `
      <section class="step">
        <div class="step-label">Step ${index + 1}</div>
        ${descriptionHtml}
        ${imgHtml}
      </section>
    `;
  }));

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>${STYLE}</style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    ${description ? `<p class="guide-description">${escapeHtml(description)}</p>` : ''}
  </header>
  <main>
    ${renderedSteps.join('\n')}
  </main>
  <footer>Generated by LocalGuide</footer>
</body>
</html>`;

  return new Blob([html], { type: 'text/html' });
}

const __api = { exportHtml };
if (typeof module !== 'undefined' && module.exports) {
  module.exports = __api;
}
if (typeof self !== 'undefined') {
  self.LocalGuide = Object.assign(self.LocalGuide || {}, __api);
}
